easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

users:
    type:     rest
    prefix: /api
    resource: '@ApiBundle/Controller/UserApiController.php'

catgories:
    type:     rest
    prefix: /api
    resource: '@ApiBundle/Controller/CategoryApiController.php'

products:
    type:     rest
    prefix: /api
    resource: '@ApiBundle/Controller/ProductApiController.php'

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

grocery:
    resource: "@GroceryBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
